// <auto-generated />
using System;
using Api.Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251221212531_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Api.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6b8a28d1-d8eb-46d4-9946-b6007dbb7c23"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Allows the user to view their details.",
                            Name = "View my details"
                        },
                        new
                        {
                            Id = new Guid("37fad974-167b-4d6f-9cc6-c57b488b72a7"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Allows the user to update their details.",
                            Name = "Update my details"
                        },
                        new
                        {
                            Id = new Guid("3fc973af-c16f-4a92-a461-3cce8f5cecf9"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Allows the user to delete their details.",
                            Name = "Delete my details"
                        },
                        new
                        {
                            Id = new Guid("0e9b858f-164d-4c75-a559-9c13d3794547"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Allows the user to view their roles.",
                            Name = "View my roles"
                        },
                        new
                        {
                            Id = new Guid("7b91219a-11ff-46c3-88b3-bd483c3a1658"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Allows the user to view project they're involved with.",
                            Name = "View my projects"
                        },
                        new
                        {
                            Id = new Guid("73fbc56a-be18-45d8-bb78-5fd8b0391b6c"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Allows the user to create projects.",
                            Name = "Create projects"
                        },
                        new
                        {
                            Id = new Guid("ab80f393-242f-4021-9ccc-f93c5d11427e"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Allows the user to view a project.",
                            Name = "View project"
                        },
                        new
                        {
                            Id = new Guid("008824e5-561a-4c51-b9cb-3d75782f1b84"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Allows the user to rename a project.",
                            Name = "Rename project"
                        },
                        new
                        {
                            Id = new Guid("d132729b-1009-48d2-a6c1-17761c8ff500"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Allows the user to update a project.",
                            Name = "Update project"
                        },
                        new
                        {
                            Id = new Guid("2ad51633-09b5-4abc-8cd7-0fef16ca08de"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Allows the user to delete a project.",
                            Name = "Delete project"
                        });
                });

            modelBuilder.Entity("Api.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("Api.Domain.Entities.ProjectUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectUsers", (string)null);
                });

            modelBuilder.Entity("Api.Domain.Entities.ProjectUserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<Guid>("ProjectUserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("ProjectUserId");

                    b.HasIndex("RoleId");

                    b.ToTable("ProjectUserRoles", (string)null);
                });

            modelBuilder.Entity("Api.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ec9607b4-eeb3-4fa2-bb21-0a728ced03f1"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The role assigned when registering for an account.",
                            Name = "General",
                            Scope = 0
                        },
                        new
                        {
                            Id = new Guid("da91b68a-e3bf-4f88-8a72-382a9b868759"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A role assigned for demo accounts.",
                            Name = "Demo",
                            Scope = 0
                        },
                        new
                        {
                            Id = new Guid("b4d50721-7c41-491b-92d7-a8213599cc2b"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Allows the user to perform all project operations, including project deletion.",
                            Name = "Owner",
                            Scope = 1
                        });
                });

            modelBuilder.Entity("Api.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("ec9607b4-eeb3-4fa2-bb21-0a728ced03f1"),
                            PermissionId = new Guid("6b8a28d1-d8eb-46d4-9946-b6007dbb7c23")
                        },
                        new
                        {
                            RoleId = new Guid("ec9607b4-eeb3-4fa2-bb21-0a728ced03f1"),
                            PermissionId = new Guid("37fad974-167b-4d6f-9cc6-c57b488b72a7")
                        },
                        new
                        {
                            RoleId = new Guid("ec9607b4-eeb3-4fa2-bb21-0a728ced03f1"),
                            PermissionId = new Guid("3fc973af-c16f-4a92-a461-3cce8f5cecf9")
                        },
                        new
                        {
                            RoleId = new Guid("ec9607b4-eeb3-4fa2-bb21-0a728ced03f1"),
                            PermissionId = new Guid("0e9b858f-164d-4c75-a559-9c13d3794547")
                        },
                        new
                        {
                            RoleId = new Guid("ec9607b4-eeb3-4fa2-bb21-0a728ced03f1"),
                            PermissionId = new Guid("73fbc56a-be18-45d8-bb78-5fd8b0391b6c")
                        },
                        new
                        {
                            RoleId = new Guid("ec9607b4-eeb3-4fa2-bb21-0a728ced03f1"),
                            PermissionId = new Guid("7b91219a-11ff-46c3-88b3-bd483c3a1658")
                        },
                        new
                        {
                            RoleId = new Guid("da91b68a-e3bf-4f88-8a72-382a9b868759"),
                            PermissionId = new Guid("6b8a28d1-d8eb-46d4-9946-b6007dbb7c23")
                        },
                        new
                        {
                            RoleId = new Guid("da91b68a-e3bf-4f88-8a72-382a9b868759"),
                            PermissionId = new Guid("0e9b858f-164d-4c75-a559-9c13d3794547")
                        },
                        new
                        {
                            RoleId = new Guid("da91b68a-e3bf-4f88-8a72-382a9b868759"),
                            PermissionId = new Guid("7b91219a-11ff-46c3-88b3-bd483c3a1658")
                        },
                        new
                        {
                            RoleId = new Guid("b4d50721-7c41-491b-92d7-a8213599cc2b"),
                            PermissionId = new Guid("ab80f393-242f-4021-9ccc-f93c5d11427e")
                        },
                        new
                        {
                            RoleId = new Guid("b4d50721-7c41-491b-92d7-a8213599cc2b"),
                            PermissionId = new Guid("008824e5-561a-4c51-b9cb-3d75782f1b84")
                        },
                        new
                        {
                            RoleId = new Guid("b4d50721-7c41-491b-92d7-a8213599cc2b"),
                            PermissionId = new Guid("d132729b-1009-48d2-a6c1-17761c8ff500")
                        },
                        new
                        {
                            RoleId = new Guid("b4d50721-7c41-491b-92d7-a8213599cc2b"),
                            PermissionId = new Guid("2ad51633-09b5-4abc-8cd7-0fef16ca08de")
                        });
                });

            modelBuilder.Entity("Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(7);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<string>("FirstName")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(5);

                    b.Property<string>("LastName")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("60345af2-506f-45d9-bc6d-1e5d16a0e105"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "h.buxton@wearewattle.com",
                            FirstName = "Harry",
                            HashedPassword = "C4F4270B5689DA8BE30D0CD9BFD6BB3FF18E9EA08EDAC567CB2FBCCAFB21B0B5-3B1D5C556AF69604D16EB2C3B5821AB8",
                            IsDeleted = false,
                            LastName = "Buxton"
                        });
                });

            modelBuilder.Entity("Api.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("60345af2-506f-45d9-bc6d-1e5d16a0e105"),
                            RoleId = new Guid("ec9607b4-eeb3-4fa2-bb21-0a728ced03f1")
                        });
                });

            modelBuilder.Entity("Api.Domain.Entities.Project", b =>
                {
                    b.HasOne("Api.Domain.Entities.User", "CreatedBy")
                        .WithMany("Projects")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Api.Domain.Entities.ProjectUser", b =>
                {
                    b.HasOne("Api.Domain.Entities.Project", "Project")
                        .WithMany("ProjectUsers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.HasOne("Api.Domain.Entities.User", "User")
                        .WithMany("ProjectUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Api.Domain.Entities.ProjectUserRole", b =>
                {
                    b.HasOne("Api.Domain.Entities.ProjectUser", "ProjectUser")
                        .WithMany("ProjectUserRoles")
                        .HasForeignKey("ProjectUserId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.HasOne("Api.Domain.Entities.Role", "Role")
                        .WithMany("ProjectUserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("ProjectUser");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Api.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("Api.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.HasOne("Api.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Api.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Api.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.HasOne("Api.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Api.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Api.Domain.Entities.Project", b =>
                {
                    b.Navigation("ProjectUsers");
                });

            modelBuilder.Entity("Api.Domain.Entities.ProjectUser", b =>
                {
                    b.Navigation("ProjectUserRoles");
                });

            modelBuilder.Entity("Api.Domain.Entities.Role", b =>
                {
                    b.Navigation("ProjectUserRoles");

                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Api.Domain.Entities.User", b =>
                {
                    b.Navigation("ProjectUsers");

                    b.Navigation("Projects");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
