// <auto-generated />
using System;
using Api.Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Api.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6b8a28d1-d8eb-46d4-9946-b6007dbb7c23"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Allows the user to view their details.",
                            Name = "View my details"
                        },
                        new
                        {
                            Id = new Guid("37fad974-167b-4d6f-9cc6-c57b488b72a7"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Allows the user to update their details.",
                            Name = "Update my details"
                        },
                        new
                        {
                            Id = new Guid("3fc973af-c16f-4a92-a461-3cce8f5cecf9"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Allows the user to delete their details.",
                            Name = "Delete my details"
                        },
                        new
                        {
                            Id = new Guid("0e9b858f-164d-4c75-a559-9c13d3794547"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Allows the user to view their roles.",
                            Name = "View my roles"
                        });
                });

            modelBuilder.Entity("Api.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("76477f30-8761-49eb-94ce-5685af2112d6"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Allows a user to perform tasks which require elevated permissions.",
                            Name = "Super Administrator",
                            Scope = 0
                        },
                        new
                        {
                            Id = new Guid("ec9607b4-eeb3-4fa2-bb21-0a728ced03f1"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Allows a user to perform most actions of the application.",
                            Name = "Standard User",
                            Scope = 0
                        },
                        new
                        {
                            Id = new Guid("da91b68a-e3bf-4f88-8a72-382a9b868759"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Prevents a user from performing write actions in the application.",
                            Name = "Read-Only User",
                            Scope = 0
                        });
                });

            modelBuilder.Entity("Api.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("76477f30-8761-49eb-94ce-5685af2112d6"),
                            PermissionId = new Guid("6b8a28d1-d8eb-46d4-9946-b6007dbb7c23")
                        },
                        new
                        {
                            RoleId = new Guid("76477f30-8761-49eb-94ce-5685af2112d6"),
                            PermissionId = new Guid("37fad974-167b-4d6f-9cc6-c57b488b72a7")
                        },
                        new
                        {
                            RoleId = new Guid("76477f30-8761-49eb-94ce-5685af2112d6"),
                            PermissionId = new Guid("3fc973af-c16f-4a92-a461-3cce8f5cecf9")
                        },
                        new
                        {
                            RoleId = new Guid("76477f30-8761-49eb-94ce-5685af2112d6"),
                            PermissionId = new Guid("0e9b858f-164d-4c75-a559-9c13d3794547")
                        },
                        new
                        {
                            RoleId = new Guid("ec9607b4-eeb3-4fa2-bb21-0a728ced03f1"),
                            PermissionId = new Guid("6b8a28d1-d8eb-46d4-9946-b6007dbb7c23")
                        },
                        new
                        {
                            RoleId = new Guid("ec9607b4-eeb3-4fa2-bb21-0a728ced03f1"),
                            PermissionId = new Guid("37fad974-167b-4d6f-9cc6-c57b488b72a7")
                        },
                        new
                        {
                            RoleId = new Guid("ec9607b4-eeb3-4fa2-bb21-0a728ced03f1"),
                            PermissionId = new Guid("3fc973af-c16f-4a92-a461-3cce8f5cecf9")
                        },
                        new
                        {
                            RoleId = new Guid("ec9607b4-eeb3-4fa2-bb21-0a728ced03f1"),
                            PermissionId = new Guid("0e9b858f-164d-4c75-a559-9c13d3794547")
                        },
                        new
                        {
                            RoleId = new Guid("da91b68a-e3bf-4f88-8a72-382a9b868759"),
                            PermissionId = new Guid("6b8a28d1-d8eb-46d4-9946-b6007dbb7c23")
                        },
                        new
                        {
                            RoleId = new Guid("da91b68a-e3bf-4f88-8a72-382a9b868759"),
                            PermissionId = new Guid("0e9b858f-164d-4c75-a559-9c13d3794547")
                        });
                });

            modelBuilder.Entity("Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(7);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<string>("FirstName")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(5);

                    b.Property<string>("LastName")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("60345af2-506f-45d9-bc6d-1e5d16a0e105"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "h.buxton@wearewattle.com",
                            FirstName = "Harry",
                            HashedPassword = "C4F4270B5689DA8BE30D0CD9BFD6BB3FF18E9EA08EDAC567CB2FBCCAFB21B0B5-3B1D5C556AF69604D16EB2C3B5821AB8",
                            IsDeleted = false,
                            LastName = "Buxton"
                        });
                });

            modelBuilder.Entity("Api.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("60345af2-506f-45d9-bc6d-1e5d16a0e105"),
                            RoleId = new Guid("76477f30-8761-49eb-94ce-5685af2112d6")
                        },
                        new
                        {
                            UserId = new Guid("60345af2-506f-45d9-bc6d-1e5d16a0e105"),
                            RoleId = new Guid("ec9607b4-eeb3-4fa2-bb21-0a728ced03f1")
                        });
                });

            modelBuilder.Entity("Api.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("Api.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Api.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Api.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Api.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Api.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Api.Domain.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
